# Generated by Django 3.1.2 on 2020-10-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='information',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('important', 'Important')], default='normal', max_length=20),
        ),
    ]
