# Generated by Django 3.1.2 on 2020-10-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0002_auto_20201004_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ('-date',)},
        ),
    ]
