# Generated by Django 3.1.2 on 2020-10-13 07:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20201013_0715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Profile',
        ),
    ]
